/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author astri
 */
public class desarrolloView extends javax.swing.JFrame {

    /**
     * Creates new form desarrolloView
     */
    public desarrolloView() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        rbtnG_Dp1.add(rbtn_2016_2017);
        rbtnG_Dp1.add(rbn_2017_2018);
        rbtnG_Dp1.add(rbn_2018_2019);
        rbtnG_Dp1.add(rbn_descono);
        
        rbtnG_Dp21.add(rbtn_Dp21_Mucho);
        rbtnG_Dp21.add(rbtn_Dp21_Regular);
        rbtnG_Dp21.add(rbtn_Dp21_Poco);
        rbtnG_Dp21.add(rbtn_Dp21_Nada);
        
        
        rbtnG_Dp22.add(rbtn_Dp22_Mucho);
        rbtnG_Dp22.add(rbtn_Dp22_Regular);
        rbtnG_Dp22.add(rbtn_Dp22_Poco);
        rbtnG_Dp22.add(rbtn_Dp22_Nada);
        
        rbtnG_Dp23.add(rbtn_Dp23_Mucho);
        rbtnG_Dp23.add(rbtn_Dp23_Regular);
        rbtnG_Dp23.add(rbtn_Dp23_Poco);
        rbtnG_Dp23.add(rbtn_Dp23_Nada);
        
        rbtnG_Dp31.add(rbtn_Dp31_Mucho);
        rbtnG_Dp31.add(rbtn_Dp31_Regular);
        rbtnG_Dp31.add(rbtn_Dp31_Poco);
        rbtnG_Dp31.add(rbtn_Dp31_Nada);
        
        rbtnG_Dp32.add(rbtn_Dp32_Mucho);
        rbtnG_Dp32.add(rbtn_Dp32_Regular);
        rbtnG_Dp32.add(rbtn_Dp32_Poco);
        rbtnG_Dp32.add(rbtn_Dp32_Nada);
        
        rbtnG_Dp33.add(rbtn_Dp33_Mucho);
        rbtnG_Dp33.add(rbtn_Dp33_Regular);
        rbtnG_Dp33.add(rbtn_Dp33_Poco);
        rbtnG_Dp33.add(rbtn_Dp33_Nada);
        
        
        rbtnG_Dp34.add(rbtn_Dp34_Mucho);
        rbtnG_Dp34.add(rbtn_Dp34_Regular);
        rbtnG_Dp34.add(rbtn_Dp34_Poco);
        rbtnG_Dp34.add(rbtn_Dp34_Nada);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnG_Dp1 = new javax.swing.ButtonGroup();
        rbtnG_Dp21 = new javax.swing.ButtonGroup();
        rbtnG_Dp22 = new javax.swing.ButtonGroup();
        rbtnG_Dp23 = new javax.swing.ButtonGroup();
        rbtnG_Dp31 = new javax.swing.ButtonGroup();
        rbtnG_Dp32 = new javax.swing.ButtonGroup();
        rbtnG_Dp33 = new javax.swing.ButtonGroup();
        rbtnG_Dp34 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnl_Dp1 = new javax.swing.JPanel();
        L_Dp11 = new javax.swing.JLabel();
        pnl_r1D = new javax.swing.JPanel();
        rbtn_2016_2017 = new javax.swing.JRadioButton();
        rbn_2017_2018 = new javax.swing.JRadioButton();
        rbn_2018_2019 = new javax.swing.JRadioButton();
        rbn_descono = new javax.swing.JRadioButton();
        checkB_Inv_Dp1 = new javax.swing.JCheckBox();
        L_Dp12 = new javax.swing.JLabel();
        pnl_Dp2 = new javax.swing.JPanel();
        L_Dp2 = new javax.swing.JLabel();
        pnl_Dr2 = new javax.swing.JPanel();
        pnl_Dp21 = new javax.swing.JPanel();
        pnl_Dr21 = new javax.swing.JPanel();
        rbtn_Dp21_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp21_Regular = new javax.swing.JRadioButton();
        rbtn_Dp21_Poco = new javax.swing.JRadioButton();
        rbtn_Dp21_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp21 = new javax.swing.JCheckBox();
        L_p21 = new javax.swing.JLabel();
        pnl_Dp22 = new javax.swing.JPanel();
        L_p22 = new javax.swing.JLabel();
        pnl_Dr22 = new javax.swing.JPanel();
        rbtn_Dp22_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp22_Regular = new javax.swing.JRadioButton();
        rbtn_Dp22_Poco = new javax.swing.JRadioButton();
        rbtn_Dp22_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp22 = new javax.swing.JCheckBox();
        pnl_Dp23 = new javax.swing.JPanel();
        pnl_Dr23 = new javax.swing.JPanel();
        rbtn_Dp23_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp23_Regular = new javax.swing.JRadioButton();
        rbtn_Dp23_Poco = new javax.swing.JRadioButton();
        rbtn_Dp23_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp23 = new javax.swing.JCheckBox();
        L_p23 = new javax.swing.JLabel();
        pnl_Dp3 = new javax.swing.JPanel();
        L_Dp31 = new javax.swing.JLabel();
        pnl_Dr3 = new javax.swing.JPanel();
        pnl_Dp31 = new javax.swing.JPanel();
        pnl_Dr31 = new javax.swing.JPanel();
        rbtn_Dp31_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp31_Regular = new javax.swing.JRadioButton();
        rbtn_Dp31_Poco = new javax.swing.JRadioButton();
        rbtn_Dp31_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp31 = new javax.swing.JCheckBox();
        L_p31 = new javax.swing.JLabel();
        pnl_Dp32 = new javax.swing.JPanel();
        L_p32 = new javax.swing.JLabel();
        pnl_Dr32 = new javax.swing.JPanel();
        rbtn_Dp32_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp32_Regular = new javax.swing.JRadioButton();
        rbtn_Dp32_Poco = new javax.swing.JRadioButton();
        rbtn_Dp32_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp32 = new javax.swing.JCheckBox();
        pnl_Dp33 = new javax.swing.JPanel();
        L_p33_1 = new javax.swing.JLabel();
        L_p33 = new javax.swing.JLabel();
        pnl_Dr33 = new javax.swing.JPanel();
        rbtn_Dp33_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp33_Regular = new javax.swing.JRadioButton();
        rbtn_Dp33_Poco = new javax.swing.JRadioButton();
        rbtn_Dp33_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp33 = new javax.swing.JCheckBox();
        pnl_Dr34 = new javax.swing.JPanel();
        L_p34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkB_Inv_Dp34 = new javax.swing.JCheckBox();
        rbtn_Dp34_Nada = new javax.swing.JRadioButton();
        rbtn_Dp34_Poco = new javax.swing.JRadioButton();
        rbtn_Dp34_Regular = new javax.swing.JRadioButton();
        rbtn_Dp34_Mucho = new javax.swing.JRadioButton();
        L_Dp32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 750));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        L_Dp11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp11.setText("1. Señale el ciclo escolar en que su escuela ha estado adscrita al Programa Nacional de Convivencia Escolar (puede");

        rbtn_2016_2017.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_2016_2017.setText("2016 - 2017");
        rbtn_2016_2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_2016_2017ActionPerformed(evt);
            }
        });

        rbn_2017_2018.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2017_2018.setText("2017 - 2018");
        rbn_2017_2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_2017_2018ActionPerformed(evt);
            }
        });

        rbn_2018_2019.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2018_2019.setText("2018-2019");

        rbn_descono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_descono.setText("Lo desconozco");

        checkB_Inv_Dp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp1.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp1.setText("Invalidar pregunta");
        checkB_Inv_Dp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1DLayout = new javax.swing.GroupLayout(pnl_r1D);
        pnl_r1D.setLayout(pnl_r1DLayout);
        pnl_r1DLayout.setHorizontalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_2016_2017)
                .addGap(60, 60, 60)
                .addComponent(rbn_2017_2018)
                .addGap(90, 90, 90)
                .addComponent(rbn_2018_2019)
                .addGap(90, 90, 90)
                .addComponent(rbn_descono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp1)
                .addGap(58, 58, 58))
        );
        pnl_r1DLayout.setVerticalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_2016_2017)
                    .addComponent(rbn_2017_2018)
                    .addComponent(rbn_2018_2019)
                    .addComponent(rbn_descono)
                    .addComponent(checkB_Inv_Dp1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        L_Dp12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp12.setText("mencionar más de uno):");

        javax.swing.GroupLayout pnl_Dp1Layout = new javax.swing.GroupLayout(pnl_Dp1);
        pnl_Dp1.setLayout(pnl_Dp1Layout);
        pnl_Dp1Layout.setHorizontalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Dp12)
                    .addComponent(L_Dp11, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp1Layout.setVerticalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp11)
                .addGap(10, 10, 10)
                .addComponent(L_Dp12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Dp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp2.setText("2. Del Programa Nacional de Convivencia Escolar, en qué medida conoce:");

        rbtn_Dp21_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Mucho.setText("Mucho");
        rbtn_Dp21_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp21_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Regular.setText("Regular");
        rbtn_Dp21_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp21_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Poco.setText("Poco");

        rbtn_Dp21_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Nada.setText("Nada");

        checkB_Inv_Dp21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp21.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp21.setText("Invalidar pregunta");
        checkB_Inv_Dp21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr21Layout = new javax.swing.GroupLayout(pnl_Dr21);
        pnl_Dr21.setLayout(pnl_Dr21Layout);
        pnl_Dr21Layout.setHorizontalGroup(
            pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp21_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp21)
                .addContainerGap())
        );
        pnl_Dr21Layout.setVerticalGroup(
            pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp21_Mucho)
                    .addComponent(rbtn_Dp21_Regular)
                    .addComponent(rbtn_Dp21_Poco)
                    .addComponent(rbtn_Dp21_Nada)
                    .addComponent(checkB_Inv_Dp21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p21.setText("El objetivo que persigue.");

        javax.swing.GroupLayout pnl_Dp21Layout = new javax.swing.GroupLayout(pnl_Dp21);
        pnl_Dp21.setLayout(pnl_Dp21Layout);
        pnl_Dp21Layout.setHorizontalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp21Layout.createSequentialGroup()
                .addComponent(L_p21, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Dr21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_Dp21Layout.setVerticalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp21Layout.createSequentialGroup()
                        .addComponent(pnl_Dr21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(L_p21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        L_p22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p22.setText("Las personas a quienes va dirigido");

        rbtn_Dp22_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Mucho.setText("Mucho");
        rbtn_Dp22_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp22_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Regular.setText("Regular");
        rbtn_Dp22_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp22_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Poco.setText("Poco");

        rbtn_Dp22_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Nada.setText("Nada");

        checkB_Inv_Dp22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp22.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp22.setText("Invalidar pregunta");
        checkB_Inv_Dp22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr22Layout = new javax.swing.GroupLayout(pnl_Dr22);
        pnl_Dr22.setLayout(pnl_Dr22Layout);
        pnl_Dr22Layout.setHorizontalGroup(
            pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp22_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp22)
                .addContainerGap())
        );
        pnl_Dr22Layout.setVerticalGroup(
            pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp22_Mucho)
                    .addComponent(rbtn_Dp22_Regular)
                    .addComponent(rbtn_Dp22_Poco)
                    .addComponent(rbtn_Dp22_Nada)
                    .addComponent(checkB_Inv_Dp22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp22Layout = new javax.swing.GroupLayout(pnl_Dp22);
        pnl_Dp22.setLayout(pnl_Dp22Layout);
        pnl_Dp22Layout.setHorizontalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp22Layout.createSequentialGroup()
                .addComponent(L_p22, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(pnl_Dr22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        pnl_Dp22Layout.setVerticalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_p22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_Dp22Layout.createSequentialGroup()
                .addComponent(pnl_Dr22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        rbtn_Dp23_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Mucho.setText("Mucho");
        rbtn_Dp23_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp23_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Regular.setText("Regular");
        rbtn_Dp23_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp23_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Poco.setText("Poco");

        rbtn_Dp23_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Nada.setText("Nada");

        checkB_Inv_Dp23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp23.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp23.setText("Invalidar pregunta");
        checkB_Inv_Dp23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr23Layout = new javax.swing.GroupLayout(pnl_Dr23);
        pnl_Dr23.setLayout(pnl_Dr23Layout);
        pnl_Dr23Layout.setHorizontalGroup(
            pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp23_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp23)
                .addContainerGap())
        );
        pnl_Dr23Layout.setVerticalGroup(
            pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp23_Mucho)
                    .addComponent(rbtn_Dp23_Regular)
                    .addComponent(rbtn_Dp23_Poco)
                    .addComponent(rbtn_Dp23_Nada)
                    .addComponent(checkB_Inv_Dp23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp23Layout = new javax.swing.GroupLayout(pnl_Dp23);
        pnl_Dp23.setLayout(pnl_Dp23Layout);
        pnl_Dp23Layout.setHorizontalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp23Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(pnl_Dr23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp23Layout.setVerticalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp23Layout.createSequentialGroup()
                .addComponent(pnl_Dr23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        L_p23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p23.setText("Los materiales diseñados (guías, manuales y cuadernos)");

        javax.swing.GroupLayout pnl_Dr2Layout = new javax.swing.GroupLayout(pnl_Dr2);
        pnl_Dr2.setLayout(pnl_Dr2Layout);
        pnl_Dr2Layout.setHorizontalGroup(
            pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dr2Layout.createSequentialGroup()
                        .addGroup(pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_Dr2Layout.createSequentialGroup()
                                .addComponent(L_p23, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_Dp23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnl_Dp21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(pnl_Dr2Layout.createSequentialGroup()
                        .addComponent(pnl_Dp22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_Dr2Layout.setVerticalGroup(
            pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_Dp22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dr2Layout.createSequentialGroup()
                        .addComponent(pnl_Dp23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(L_p23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_Dp2Layout = new javax.swing.GroupLayout(pnl_Dp2);
        pnl_Dp2.setLayout(pnl_Dp2Layout);
        pnl_Dp2Layout.setHorizontalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_Dr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnl_Dp2Layout.setVerticalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        L_Dp31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp31.setText("3. En qué medida considera que se han cumplido los alcances del Programa Nacional de Convivencia Escolar en su");

        rbtn_Dp31_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Mucho.setText("Mucho");
        rbtn_Dp31_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp31_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp31_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Regular.setText("Regular");
        rbtn_Dp31_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp31_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp31_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Poco.setText("Poco");

        rbtn_Dp31_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Nada.setText("Nada");

        checkB_Inv_Dp31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp31.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp31.setText("Invalidar pregunta");
        checkB_Inv_Dp31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr31Layout = new javax.swing.GroupLayout(pnl_Dr31);
        pnl_Dr31.setLayout(pnl_Dr31Layout);
        pnl_Dr31Layout.setHorizontalGroup(
            pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp31_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp31)
                .addContainerGap())
        );
        pnl_Dr31Layout.setVerticalGroup(
            pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp31_Mucho)
                    .addComponent(rbtn_Dp31_Regular)
                    .addComponent(rbtn_Dp31_Poco)
                    .addComponent(rbtn_Dp31_Nada)
                    .addComponent(checkB_Inv_Dp31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p31.setText("La capacitación del personal docente");

        javax.swing.GroupLayout pnl_Dp31Layout = new javax.swing.GroupLayout(pnl_Dp31);
        pnl_Dp31.setLayout(pnl_Dp31Layout);
        pnl_Dp31Layout.setHorizontalGroup(
            pnl_Dp31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp31Layout.createSequentialGroup()
                .addComponent(L_p31, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Dr31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp31Layout.setVerticalGroup(
            pnl_Dp31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Dp31Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_Dr31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L_p31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        L_p32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p32.setText("La capacitación de las madres, padres y tutores");

        rbtn_Dp32_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Mucho.setText("Mucho");
        rbtn_Dp32_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp32_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Regular.setText("Regular");
        rbtn_Dp32_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp32_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Poco.setText("Poco");
        rbtn_Dp32_Poco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_PocoActionPerformed(evt);
            }
        });

        rbtn_Dp32_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Nada.setText("Nada");

        checkB_Inv_Dp32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp32.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp32.setText("Invalidar pregunta");
        checkB_Inv_Dp32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr32Layout = new javax.swing.GroupLayout(pnl_Dr32);
        pnl_Dr32.setLayout(pnl_Dr32Layout);
        pnl_Dr32Layout.setHorizontalGroup(
            pnl_Dr32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp32_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp32)
                .addContainerGap())
        );
        pnl_Dr32Layout.setVerticalGroup(
            pnl_Dr32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp32_Mucho)
                    .addComponent(rbtn_Dp32_Regular)
                    .addComponent(rbtn_Dp32_Poco)
                    .addComponent(rbtn_Dp32_Nada)
                    .addComponent(checkB_Inv_Dp32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp32Layout = new javax.swing.GroupLayout(pnl_Dp32);
        pnl_Dp32.setLayout(pnl_Dp32Layout);
        pnl_Dp32Layout.setHorizontalGroup(
            pnl_Dp32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp32Layout.createSequentialGroup()
                .addComponent(L_p32, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(pnl_Dr32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp32Layout.setVerticalGroup(
            pnl_Dp32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp32Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L_p32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnl_Dr32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        L_p33_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p33_1.setText("y cuadernos).");

        L_p33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p33.setText("La utilidad de los materiales diseñados (guías, manuales ");

        rbtn_Dp33_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Mucho.setText("Mucho");
        rbtn_Dp33_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp33_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp33_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Regular.setText("Regular");
        rbtn_Dp33_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp33_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp33_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Poco.setText("Poco");

        rbtn_Dp33_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Nada.setText("Nada");

        checkB_Inv_Dp33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp33.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp33.setText("Invalidar pregunta");
        checkB_Inv_Dp33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr33Layout = new javax.swing.GroupLayout(pnl_Dr33);
        pnl_Dr33.setLayout(pnl_Dr33Layout);
        pnl_Dr33Layout.setHorizontalGroup(
            pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp33_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dr33Layout.setVerticalGroup(
            pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp33_Mucho)
                    .addComponent(rbtn_Dp33_Regular)
                    .addComponent(rbtn_Dp33_Poco)
                    .addComponent(rbtn_Dp33_Nada)
                    .addComponent(checkB_Inv_Dp33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp33Layout = new javax.swing.GroupLayout(pnl_Dp33);
        pnl_Dp33.setLayout(pnl_Dp33Layout);
        pnl_Dp33Layout.setHorizontalGroup(
            pnl_Dp33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp33Layout.createSequentialGroup()
                .addGroup(pnl_Dp33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_p33)
                    .addComponent(L_p33_1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(pnl_Dr33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp33Layout.setVerticalGroup(
            pnl_Dp33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_Dp33Layout.createSequentialGroup()
                        .addComponent(L_p33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L_p33_1))
                    .addComponent(pnl_Dr33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        L_p34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p34.setText("La atención y prevención de la violencia");

        checkB_Inv_Dp34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp34.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp34.setText("Invalidar pregunta");
        checkB_Inv_Dp34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp34ActionPerformed(evt);
            }
        });

        rbtn_Dp34_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Nada.setText("Nada");

        rbtn_Dp34_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Poco.setText("Poco");

        rbtn_Dp34_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Regular.setText("Regular");
        rbtn_Dp34_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp34_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp34_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Mucho.setText("Mucho");
        rbtn_Dp34_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp34_MuchoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp34_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp34_Regular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rbtn_Dp34_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp34_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp34)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp34_Nada)
                    .addComponent(rbtn_Dp34_Poco)
                    .addComponent(rbtn_Dp34_Regular)
                    .addComponent(rbtn_Dp34_Mucho)
                    .addComponent(checkB_Inv_Dp34))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_Dr34Layout = new javax.swing.GroupLayout(pnl_Dr34);
        pnl_Dr34.setLayout(pnl_Dr34Layout);
        pnl_Dr34Layout.setHorizontalGroup(
            pnl_Dr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr34Layout.createSequentialGroup()
                .addComponent(L_p34, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dr34Layout.setVerticalGroup(
            pnl_Dr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_p34, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dr3Layout = new javax.swing.GroupLayout(pnl_Dr3);
        pnl_Dr3.setLayout(pnl_Dr3Layout);
        pnl_Dr3Layout.setHorizontalGroup(
            pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr3Layout.createSequentialGroup()
                .addGroup(pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnl_Dp31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_Dp32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_Dp33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_Dr34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dr3Layout.setVerticalGroup(
            pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Dr34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        L_Dp32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp32.setText("escuela, en relación con:");

        javax.swing.GroupLayout pnl_Dp3Layout = new javax.swing.GroupLayout(pnl_Dp3);
        pnl_Dp3.setLayout(pnl_Dp3Layout);
        pnl_Dp3Layout.setHorizontalGroup(
            pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp3Layout.createSequentialGroup()
                .addGroup(pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(L_Dp32, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Dp3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_Dr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Dp31, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp3Layout.setVerticalGroup(
            pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp31, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Dp32, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Dp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Dp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnl_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_2016_2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_2016_2017ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_2016_2017ActionPerformed

    private void rbn_2017_2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_2017_2018ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_2017_2018ActionPerformed

    private void rbtn_Dp21_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_MuchoActionPerformed

    private void rbtn_Dp21_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_RegularActionPerformed

    private void rbtn_Dp22_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_MuchoActionPerformed

    private void rbtn_Dp22_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_RegularActionPerformed

    private void rbtn_Dp23_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_MuchoActionPerformed

    private void rbtn_Dp23_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_RegularActionPerformed

    private void checkB_Inv_Dp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp1ActionPerformed

    private void checkB_Inv_Dp21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp21ActionPerformed

    private void checkB_Inv_Dp22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp22ActionPerformed

    private void checkB_Inv_Dp23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp23ActionPerformed

    private void rbtn_Dp31_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp31_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp31_MuchoActionPerformed

    private void rbtn_Dp31_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp31_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp31_RegularActionPerformed

    private void checkB_Inv_Dp31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp31ActionPerformed

    private void rbtn_Dp32_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_MuchoActionPerformed

    private void rbtn_Dp32_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_RegularActionPerformed

    private void checkB_Inv_Dp32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp32ActionPerformed

    private void rbtn_Dp33_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp33_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp33_MuchoActionPerformed

    private void rbtn_Dp33_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp33_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp33_RegularActionPerformed

    private void checkB_Inv_Dp33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp33ActionPerformed

    private void rbtn_Dp34_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp34_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp34_MuchoActionPerformed

    private void rbtn_Dp34_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp34_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp34_RegularActionPerformed

    private void checkB_Inv_Dp34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp34ActionPerformed

    private void rbtn_Dp32_PocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_PocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_PocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desarrolloView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Dp11;
    private javax.swing.JLabel L_Dp12;
    private javax.swing.JLabel L_Dp2;
    private javax.swing.JLabel L_Dp31;
    private javax.swing.JLabel L_Dp32;
    private javax.swing.JLabel L_p21;
    private javax.swing.JLabel L_p22;
    private javax.swing.JLabel L_p23;
    private javax.swing.JLabel L_p31;
    private javax.swing.JLabel L_p32;
    private javax.swing.JLabel L_p33;
    private javax.swing.JLabel L_p33_1;
    private javax.swing.JLabel L_p34;
    private javax.swing.JCheckBox checkB_Inv_Dp1;
    private javax.swing.JCheckBox checkB_Inv_Dp21;
    private javax.swing.JCheckBox checkB_Inv_Dp22;
    private javax.swing.JCheckBox checkB_Inv_Dp23;
    private javax.swing.JCheckBox checkB_Inv_Dp31;
    private javax.swing.JCheckBox checkB_Inv_Dp32;
    private javax.swing.JCheckBox checkB_Inv_Dp33;
    private javax.swing.JCheckBox checkB_Inv_Dp34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_Dp1;
    private javax.swing.JPanel pnl_Dp2;
    private javax.swing.JPanel pnl_Dp21;
    private javax.swing.JPanel pnl_Dp22;
    private javax.swing.JPanel pnl_Dp23;
    private javax.swing.JPanel pnl_Dp3;
    private javax.swing.JPanel pnl_Dp31;
    private javax.swing.JPanel pnl_Dp32;
    private javax.swing.JPanel pnl_Dp33;
    private javax.swing.JPanel pnl_Dr2;
    private javax.swing.JPanel pnl_Dr21;
    private javax.swing.JPanel pnl_Dr22;
    private javax.swing.JPanel pnl_Dr23;
    private javax.swing.JPanel pnl_Dr3;
    private javax.swing.JPanel pnl_Dr31;
    private javax.swing.JPanel pnl_Dr32;
    private javax.swing.JPanel pnl_Dr33;
    private javax.swing.JPanel pnl_Dr34;
    private javax.swing.JPanel pnl_r1D;
    private javax.swing.JRadioButton rbn_2017_2018;
    private javax.swing.JRadioButton rbn_2018_2019;
    private javax.swing.JRadioButton rbn_descono;
    private javax.swing.ButtonGroup rbtnG_Dp1;
    private javax.swing.ButtonGroup rbtnG_Dp21;
    private javax.swing.ButtonGroup rbtnG_Dp22;
    private javax.swing.ButtonGroup rbtnG_Dp23;
    private javax.swing.ButtonGroup rbtnG_Dp31;
    private javax.swing.ButtonGroup rbtnG_Dp32;
    private javax.swing.ButtonGroup rbtnG_Dp33;
    private javax.swing.ButtonGroup rbtnG_Dp34;
    private javax.swing.JRadioButton rbtn_2016_2017;
    private javax.swing.JRadioButton rbtn_Dp21_Mucho;
    private javax.swing.JRadioButton rbtn_Dp21_Nada;
    private javax.swing.JRadioButton rbtn_Dp21_Poco;
    private javax.swing.JRadioButton rbtn_Dp21_Regular;
    private javax.swing.JRadioButton rbtn_Dp22_Mucho;
    private javax.swing.JRadioButton rbtn_Dp22_Nada;
    private javax.swing.JRadioButton rbtn_Dp22_Poco;
    private javax.swing.JRadioButton rbtn_Dp22_Regular;
    private javax.swing.JRadioButton rbtn_Dp23_Mucho;
    private javax.swing.JRadioButton rbtn_Dp23_Nada;
    private javax.swing.JRadioButton rbtn_Dp23_Poco;
    private javax.swing.JRadioButton rbtn_Dp23_Regular;
    private javax.swing.JRadioButton rbtn_Dp31_Mucho;
    private javax.swing.JRadioButton rbtn_Dp31_Nada;
    private javax.swing.JRadioButton rbtn_Dp31_Poco;
    private javax.swing.JRadioButton rbtn_Dp31_Regular;
    private javax.swing.JRadioButton rbtn_Dp32_Mucho;
    private javax.swing.JRadioButton rbtn_Dp32_Nada;
    private javax.swing.JRadioButton rbtn_Dp32_Poco;
    private javax.swing.JRadioButton rbtn_Dp32_Regular;
    private javax.swing.JRadioButton rbtn_Dp33_Mucho;
    private javax.swing.JRadioButton rbtn_Dp33_Nada;
    private javax.swing.JRadioButton rbtn_Dp33_Poco;
    private javax.swing.JRadioButton rbtn_Dp33_Regular;
    private javax.swing.JRadioButton rbtn_Dp34_Mucho;
    private javax.swing.JRadioButton rbtn_Dp34_Nada;
    private javax.swing.JRadioButton rbtn_Dp34_Poco;
    private javax.swing.JRadioButton rbtn_Dp34_Regular;
    // End of variables declaration//GEN-END:variables
}
