/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author astri
 */
public class desarrolloView_0 extends javax.swing.JFrame {

    /**
     * Creates new form desarrolloView
     */
    public desarrolloView_0() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        rbtnG_Dp1.add(rbtn_2016_2017);
        rbtnG_Dp1.add(rbn_2017_2018);
        rbtnG_Dp1.add(rbn_2018_2019);
        rbtnG_Dp1.add(rbn_descono);
        
        rbtnG_Dp21.add(rbtn_Dp21_Mucho);
        rbtnG_Dp21.add(rbtn_Dp21_Regular);
        rbtnG_Dp21.add(rbtn_Dp21_Poco);
        rbtnG_Dp21.add(rbtn_Dp21_Nada);
        
        
        rbtnG_Dp22.add(rbtn_Dp22_Mucho);
        rbtnG_Dp22.add(rbtn_Dp22_Regular);
        rbtnG_Dp22.add(rbtn_Dp22_Poco);
        rbtnG_Dp22.add(rbtn_Dp22_Nada);
        
        rbtnG_Dp23.add(rbtn_Dp23_Mucho);
        rbtnG_Dp23.add(rbtn_Dp23_Regular);
        rbtnG_Dp23.add(rbtn_Dp23_Poco);
        rbtnG_Dp23.add(rbtn_Dp23_Nada);
        
        rbtnG_Dp31.add(rbtn_Dp31_Mucho1);
        rbtnG_Dp31.add(rbtn_Dp31_Regular1);
        rbtnG_Dp31.add(rbtn_Dp31_Poco1);
        rbtnG_Dp31.add(rbtn_Dp31_Nada1);
        
        rbtnG_Dp32.add(rbtn_Dp32_Mucho1);
        rbtnG_Dp32.add(rbtn_Dp32_Regular1);
        rbtnG_Dp32.add(rbtn_Dp32_Poco1);
        rbtnG_Dp32.add(rbtn_Dp32_Nada1);
        
        rbtnG_Dp33.add(rbtn_Dp33_Mucho1);
        rbtnG_Dp33.add(rbtn_Dp33_Regular1);
        rbtnG_Dp33.add(rbtn_Dp33_Poco1);
        rbtnG_Dp33.add(rbtn_Dp33_Nada1);
        
       
        rbtnG_Dp34.add(rbtn_Dp34_Mucho);
        rbtnG_Dp34.add(rbtn_Dp34_Regular);
        rbtnG_Dp34.add(rbtn_Dp34_Poco);
        rbtnG_Dp34.add(rbtn_Dp34_Nada);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnG_Dp1 = new javax.swing.ButtonGroup();
        rbtnG_Dp21 = new javax.swing.ButtonGroup();
        rbtnG_Dp22 = new javax.swing.ButtonGroup();
        rbtnG_Dp23 = new javax.swing.ButtonGroup();
        rbtnG_Dp31 = new javax.swing.ButtonGroup();
        rbtnG_Dp32 = new javax.swing.ButtonGroup();
        rbtnG_Dp33 = new javax.swing.ButtonGroup();
        rbtnG_Dp34 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnl_Dp1 = new javax.swing.JPanel();
        L_Dp11 = new javax.swing.JLabel();
        pnl_r1D = new javax.swing.JPanel();
        rbtn_2016_2017 = new javax.swing.JRadioButton();
        rbn_2017_2018 = new javax.swing.JRadioButton();
        rbn_2018_2019 = new javax.swing.JRadioButton();
        rbn_descono = new javax.swing.JRadioButton();
        checkB_Inv_Dp1 = new javax.swing.JCheckBox();
        L_Dp12 = new javax.swing.JLabel();
        pnl_Dp2 = new javax.swing.JPanel();
        L_Dp2 = new javax.swing.JLabel();
        pnl_Dr2 = new javax.swing.JPanel();
        pnl_Dp21 = new javax.swing.JPanel();
        pnl_Dr21 = new javax.swing.JPanel();
        rbtn_Dp21_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp21_Regular = new javax.swing.JRadioButton();
        rbtn_Dp21_Poco = new javax.swing.JRadioButton();
        rbtn_Dp21_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp21 = new javax.swing.JCheckBox();
        L_p21 = new javax.swing.JLabel();
        pnl_Dp22 = new javax.swing.JPanel();
        pnl_Dr22 = new javax.swing.JPanel();
        rbtn_Dp22_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp22_Regular = new javax.swing.JRadioButton();
        rbtn_Dp22_Poco = new javax.swing.JRadioButton();
        rbtn_Dp22_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp22 = new javax.swing.JCheckBox();
        L_p22 = new javax.swing.JLabel();
        pnl_Dp23 = new javax.swing.JPanel();
        pnl_Dr23 = new javax.swing.JPanel();
        rbtn_Dp23_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp23_Regular = new javax.swing.JRadioButton();
        rbtn_Dp23_Poco = new javax.swing.JRadioButton();
        rbtn_Dp23_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp23 = new javax.swing.JCheckBox();
        L_p23 = new javax.swing.JLabel();
        L_p25 = new javax.swing.JLabel();
        pnl_Dp4 = new javax.swing.JPanel();
        L_Dp33 = new javax.swing.JLabel();
        pnl_Dr4 = new javax.swing.JPanel();
        pnl_Dp34 = new javax.swing.JPanel();
        pnl_Dr31 = new javax.swing.JPanel();
        rbtn_Dp31_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp31_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp31_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp31_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp35 = new javax.swing.JCheckBox();
        L_p35 = new javax.swing.JLabel();
        pnl_Dp35 = new javax.swing.JPanel();
        L_p36 = new javax.swing.JLabel();
        pnl_Dr3 = new javax.swing.JPanel();
        rbtn_Dp32_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp32_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp32_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp32_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp36 = new javax.swing.JCheckBox();
        L_p39 = new javax.swing.JLabel();
        pnl_Dp36 = new javax.swing.JPanel();
        L_p33_2 = new javax.swing.JLabel();
        L_p37 = new javax.swing.JLabel();
        pnl_Dr33 = new javax.swing.JPanel();
        rbtn_Dp33_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp33_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp33_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp33_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp37 = new javax.swing.JCheckBox();
        pnl_Dr38 = new javax.swing.JPanel();
        L_p38 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        checkB_Inv_Dp34 = new javax.swing.JCheckBox();
        rbtn_Dp34_Nada = new javax.swing.JRadioButton();
        rbtn_Dp34_Poco = new javax.swing.JRadioButton();
        rbtn_Dp34_Regular = new javax.swing.JRadioButton();
        rbtn_Dp34_Mucho = new javax.swing.JRadioButton();
        L_Dp34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_DAtras = new javax.swing.JButton();
        btn_DSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 750));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 1500));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 750));

        L_Dp11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp11.setText("1. Señale el ciclo escolar en que su escuela ha estado adscrita al Programa Nacional de Convivencia Escolar (puede");

        rbtn_2016_2017.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_2016_2017.setText("2016 - 2017");
        rbtn_2016_2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_2016_2017ActionPerformed(evt);
            }
        });

        rbn_2017_2018.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2017_2018.setText("2017 - 2018");
        rbn_2017_2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_2017_2018ActionPerformed(evt);
            }
        });

        rbn_2018_2019.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2018_2019.setText("2018-2019");

        rbn_descono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_descono.setText("Lo desconozco");

        checkB_Inv_Dp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp1.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp1.setText("Invalidar pregunta");
        checkB_Inv_Dp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1DLayout = new javax.swing.GroupLayout(pnl_r1D);
        pnl_r1D.setLayout(pnl_r1DLayout);
        pnl_r1DLayout.setHorizontalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_2016_2017)
                .addGap(49, 49, 49)
                .addComponent(rbn_2017_2018)
                .addGap(90, 90, 90)
                .addComponent(rbn_2018_2019)
                .addGap(90, 90, 90)
                .addComponent(rbn_descono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_r1DLayout.setVerticalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_2016_2017)
                    .addComponent(rbn_2017_2018)
                    .addComponent(rbn_2018_2019)
                    .addComponent(rbn_descono)
                    .addComponent(checkB_Inv_Dp1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Dp12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp12.setText("mencionar más de uno):");

        javax.swing.GroupLayout pnl_Dp1Layout = new javax.swing.GroupLayout(pnl_Dp1);
        pnl_Dp1.setLayout(pnl_Dp1Layout);
        pnl_Dp1Layout.setHorizontalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Dp11, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Dp1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(L_Dp12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnl_Dp1Layout.setVerticalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Dp12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        L_Dp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp2.setText("2. Del Programa Nacional de Convivencia Escolar, en qué medida conoce:");

        rbtn_Dp21_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Mucho.setText("Mucho");
        rbtn_Dp21_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp21_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Regular.setText("Regular");
        rbtn_Dp21_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp21_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Poco.setText("Poco");

        rbtn_Dp21_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Nada.setText("Nada");

        checkB_Inv_Dp21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp21.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp21.setText("Invalidar pregunta");
        checkB_Inv_Dp21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr21Layout = new javax.swing.GroupLayout(pnl_Dr21);
        pnl_Dr21.setLayout(pnl_Dr21Layout);
        pnl_Dr21Layout.setHorizontalGroup(
            pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr21Layout.createSequentialGroup()
                .addComponent(rbtn_Dp21_Mucho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp21)
                .addContainerGap())
        );
        pnl_Dr21Layout.setVerticalGroup(
            pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp21_Mucho)
                    .addComponent(rbtn_Dp21_Regular)
                    .addComponent(rbtn_Dp21_Poco)
                    .addComponent(rbtn_Dp21_Nada)
                    .addComponent(checkB_Inv_Dp21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p21.setText("El objetivo que persigue.");

        javax.swing.GroupLayout pnl_Dp21Layout = new javax.swing.GroupLayout(pnl_Dp21);
        pnl_Dp21.setLayout(pnl_Dp21Layout);
        pnl_Dp21Layout.setHorizontalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p21, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(pnl_Dr21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp21Layout.setVerticalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp21Layout.createSequentialGroup()
                        .addComponent(L_p21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnl_Dr21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        rbtn_Dp22_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Mucho.setText("Mucho");
        rbtn_Dp22_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp22_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Regular.setText("Regular");
        rbtn_Dp22_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp22_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Poco.setText("Poco");

        rbtn_Dp22_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Nada.setText("Nada");

        checkB_Inv_Dp22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp22.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp22.setText("Invalidar pregunta");
        checkB_Inv_Dp22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr22Layout = new javax.swing.GroupLayout(pnl_Dr22);
        pnl_Dr22.setLayout(pnl_Dr22Layout);
        pnl_Dr22Layout.setHorizontalGroup(
            pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp22_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dr22Layout.setVerticalGroup(
            pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp22_Mucho)
                    .addComponent(rbtn_Dp22_Regular)
                    .addComponent(rbtn_Dp22_Poco)
                    .addComponent(rbtn_Dp22_Nada)
                    .addComponent(checkB_Inv_Dp22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p22.setText("Las personas a quienes va dirigido");

        javax.swing.GroupLayout pnl_Dp22Layout = new javax.swing.GroupLayout(pnl_Dp22);
        pnl_Dp22.setLayout(pnl_Dp22Layout);
        pnl_Dp22Layout.setHorizontalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p22, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(pnl_Dr22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp22Layout.setVerticalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_p22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_Dr22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rbtn_Dp23_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Mucho.setText("Mucho");
        rbtn_Dp23_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp23_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Regular.setText("Regular");
        rbtn_Dp23_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp23_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Poco.setText("Poco");

        rbtn_Dp23_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Nada.setText("Nada");

        checkB_Inv_Dp23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp23.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp23.setText("Invalidar pregunta");
        checkB_Inv_Dp23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr23Layout = new javax.swing.GroupLayout(pnl_Dr23);
        pnl_Dr23.setLayout(pnl_Dr23Layout);
        pnl_Dr23Layout.setHorizontalGroup(
            pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp23_Mucho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp23)
                .addGap(15, 15, 15))
        );
        pnl_Dr23Layout.setVerticalGroup(
            pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dr23Layout.createSequentialGroup()
                        .addGroup(pnl_Dr23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_Dp23_Regular)
                            .addComponent(rbtn_Dp23_Poco)
                            .addComponent(rbtn_Dp23_Nada)
                            .addComponent(checkB_Inv_Dp23))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rbtn_Dp23_Mucho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        L_p23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p23.setText("Los materiales diseñados (guías, manuales ");

        L_p25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p25.setText("y cuadernos)");

        javax.swing.GroupLayout pnl_Dp23Layout = new javax.swing.GroupLayout(pnl_Dp23);
        pnl_Dp23.setLayout(pnl_Dp23Layout);
        pnl_Dp23Layout.setHorizontalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_p25, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_p23, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(pnl_Dr23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnl_Dp23Layout.setVerticalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_p25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_Dp23Layout.createSequentialGroup()
                .addComponent(pnl_Dr23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dr2Layout = new javax.swing.GroupLayout(pnl_Dr2);
        pnl_Dr2.setLayout(pnl_Dr2Layout);
        pnl_Dr2Layout.setHorizontalGroup(
            pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Dp21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp23, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl_Dr2Layout.setVerticalGroup(
            pnl_Dr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp2Layout = new javax.swing.GroupLayout(pnl_Dp2);
        pnl_Dp2.setLayout(pnl_Dp2Layout);
        pnl_Dp2Layout.setHorizontalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addComponent(pnl_Dr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        pnl_Dp2Layout.setVerticalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnl_Dr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        L_Dp33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp33.setText("3. En qué medida considera que se han cumplido los alcances del Programa Nacional de Convivencia Escolar en su");

        rbtn_Dp31_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Mucho1.setText("Mucho");
        rbtn_Dp31_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp31_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp31_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Regular1.setText("Regular");
        rbtn_Dp31_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp31_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp31_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Poco1.setText("Poco");

        rbtn_Dp31_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp31_Nada1.setText("Nada");

        checkB_Inv_Dp35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp35.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp35.setText("Invalidar pregunta");
        checkB_Inv_Dp35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr31Layout = new javax.swing.GroupLayout(pnl_Dr31);
        pnl_Dr31.setLayout(pnl_Dr31Layout);
        pnl_Dr31Layout.setHorizontalGroup(
            pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp31_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp31_Nada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp35)
                .addContainerGap())
        );
        pnl_Dr31Layout.setVerticalGroup(
            pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp31_Mucho1)
                    .addComponent(rbtn_Dp31_Regular1)
                    .addComponent(rbtn_Dp31_Poco1)
                    .addComponent(rbtn_Dp31_Nada1)
                    .addComponent(checkB_Inv_Dp35))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p35.setText("La capacitación del personal docente");

        javax.swing.GroupLayout pnl_Dp34Layout = new javax.swing.GroupLayout(pnl_Dp34);
        pnl_Dp34.setLayout(pnl_Dp34Layout);
        pnl_Dp34Layout.setHorizontalGroup(
            pnl_Dp34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p35, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(pnl_Dr31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp34Layout.setVerticalGroup(
            pnl_Dp34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_Dp34Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_Dr31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L_p35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        L_p36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p36.setText("La capacitación de las madres, padres");

        rbtn_Dp32_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Mucho1.setText("Mucho");
        rbtn_Dp32_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp32_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Regular1.setText("Regular");
        rbtn_Dp32_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp32_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Poco1.setText("Poco");
        rbtn_Dp32_Poco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp32_Poco1ActionPerformed(evt);
            }
        });

        rbtn_Dp32_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp32_Nada1.setText("Nada");

        checkB_Inv_Dp36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp36.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp36.setText("Invalidar pregunta");
        checkB_Inv_Dp36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr3Layout = new javax.swing.GroupLayout(pnl_Dr3);
        pnl_Dr3.setLayout(pnl_Dr3Layout);
        pnl_Dr3Layout.setHorizontalGroup(
            pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp32_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp32_Nada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp36)
                .addContainerGap())
        );
        pnl_Dr3Layout.setVerticalGroup(
            pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp32_Mucho1)
                    .addComponent(rbtn_Dp32_Regular1)
                    .addComponent(rbtn_Dp32_Poco1)
                    .addComponent(rbtn_Dp32_Nada1)
                    .addComponent(checkB_Inv_Dp36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p39.setText("y tutores");

        javax.swing.GroupLayout pnl_Dp35Layout = new javax.swing.GroupLayout(pnl_Dp35);
        pnl_Dp35.setLayout(pnl_Dp35Layout);
        pnl_Dp35Layout.setHorizontalGroup(
            pnl_Dp35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_p36, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_p39, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Dr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp35Layout.setVerticalGroup(
            pnl_Dp35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp35Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_Dp35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Dr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_Dp35Layout.createSequentialGroup()
                        .addComponent(L_p36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L_p39)))
                .addContainerGap())
        );

        L_p33_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p33_2.setText("(guías, manuales  y cuadernos).");

        L_p37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p37.setText("La utilidad de los materiales diseñados ");

        rbtn_Dp33_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Mucho1.setText("Mucho");
        rbtn_Dp33_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp33_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp33_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Regular1.setText("Regular");
        rbtn_Dp33_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp33_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp33_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Poco1.setText("Poco");

        rbtn_Dp33_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp33_Nada1.setText("Nada");

        checkB_Inv_Dp37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp37.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp37.setText("Invalidar pregunta");
        checkB_Inv_Dp37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Dr33Layout = new javax.swing.GroupLayout(pnl_Dr33);
        pnl_Dr33.setLayout(pnl_Dr33Layout);
        pnl_Dr33Layout.setHorizontalGroup(
            pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp33_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp33_Nada1)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dr33Layout.setVerticalGroup(
            pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp33_Mucho1)
                    .addComponent(rbtn_Dp33_Regular1)
                    .addComponent(rbtn_Dp33_Poco1)
                    .addComponent(rbtn_Dp33_Nada1)
                    .addComponent(checkB_Inv_Dp37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp36Layout = new javax.swing.GroupLayout(pnl_Dp36);
        pnl_Dp36.setLayout(pnl_Dp36Layout);
        pnl_Dp36Layout.setHorizontalGroup(
            pnl_Dp36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_p37)
                    .addComponent(L_p33_2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addComponent(pnl_Dr33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnl_Dp36Layout.setVerticalGroup(
            pnl_Dp36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp36Layout.createSequentialGroup()
                        .addComponent(pnl_Dr33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_Dp36Layout.createSequentialGroup()
                        .addComponent(L_p37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_p33_2))))
        );

        L_p38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p38.setText("La atención y prevención de la violencia");

        checkB_Inv_Dp34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp34.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp34.setText("Invalidar pregunta");
        checkB_Inv_Dp34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp34ActionPerformed(evt);
            }
        });

        rbtn_Dp34_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Nada.setText("Nada");

        rbtn_Dp34_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Poco.setText("Poco");

        rbtn_Dp34_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Regular.setText("Regular");
        rbtn_Dp34_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp34_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp34_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp34_Mucho.setText("Mucho");
        rbtn_Dp34_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp34_MuchoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp34_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp34_Regular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rbtn_Dp34_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp34_Nada)
                .addGap(100, 100, 100)
                .addComponent(checkB_Inv_Dp34)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp34_Nada)
                    .addComponent(rbtn_Dp34_Poco)
                    .addComponent(rbtn_Dp34_Regular)
                    .addComponent(rbtn_Dp34_Mucho)
                    .addComponent(checkB_Inv_Dp34))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_Dr38Layout = new javax.swing.GroupLayout(pnl_Dr38);
        pnl_Dr38.setLayout(pnl_Dr38Layout);
        pnl_Dr38Layout.setHorizontalGroup(
            pnl_Dr38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p38, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnl_Dr38Layout.setVerticalGroup(
            pnl_Dr38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dr38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_p38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dr4Layout = new javax.swing.GroupLayout(pnl_Dr4);
        pnl_Dr4.setLayout(pnl_Dr4Layout);
        pnl_Dr4Layout.setHorizontalGroup(
            pnl_Dr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Dp36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_Dr38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_Dr4Layout.createSequentialGroup()
                .addGroup(pnl_Dr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_Dp35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_Dr4Layout.setVerticalGroup(
            pnl_Dr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dr4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Dr38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        L_Dp34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp34.setText("escuela, en relación con:");

        javax.swing.GroupLayout pnl_Dp4Layout = new javax.swing.GroupLayout(pnl_Dp4);
        pnl_Dp4.setLayout(pnl_Dp4Layout);
        pnl_Dp4Layout.setHorizontalGroup(
            pnl_Dp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp4Layout.createSequentialGroup()
                .addGroup(pnl_Dp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(L_Dp33, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Dp4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(L_Dp34, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp4Layout.setVerticalGroup(
            pnl_Dp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp33, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Dp34, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_DAtras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DAtras.setText("Atrás");
        btn_DAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DAtrasActionPerformed(evt);
            }
        });

        btn_DSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DSiguiente.setText("Siguiente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btn_DAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(btn_DSiguiente)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DAtras)
                    .addComponent(btn_DSiguiente))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnl_Dp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_Dp2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_Dp4, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_2016_2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_2016_2017ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_2016_2017ActionPerformed

    private void rbn_2017_2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_2017_2018ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_2017_2018ActionPerformed

    private void rbtn_Dp21_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_MuchoActionPerformed

    private void rbtn_Dp21_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_RegularActionPerformed

    private void rbtn_Dp22_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_MuchoActionPerformed

    private void rbtn_Dp22_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_RegularActionPerformed

    private void rbtn_Dp23_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_MuchoActionPerformed

    private void rbtn_Dp23_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_RegularActionPerformed

    private void checkB_Inv_Dp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp1ActionPerformed

    private void checkB_Inv_Dp21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp21ActionPerformed

    private void checkB_Inv_Dp22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp22ActionPerformed

    private void checkB_Inv_Dp23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp23ActionPerformed

    private void rbtn_Dp31_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp31_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp31_Mucho1ActionPerformed

    private void rbtn_Dp31_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp31_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp31_Regular1ActionPerformed

    private void checkB_Inv_Dp35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp35ActionPerformed

    private void rbtn_Dp32_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_Mucho1ActionPerformed

    private void rbtn_Dp32_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_Regular1ActionPerformed

    private void rbtn_Dp32_Poco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp32_Poco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp32_Poco1ActionPerformed

    private void checkB_Inv_Dp36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp36ActionPerformed

    private void rbtn_Dp33_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp33_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp33_Mucho1ActionPerformed

    private void rbtn_Dp33_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp33_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp33_Regular1ActionPerformed

    private void checkB_Inv_Dp37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp37ActionPerformed

    private void checkB_Inv_Dp34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp34ActionPerformed

    private void rbtn_Dp34_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp34_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp34_RegularActionPerformed

    private void rbtn_Dp34_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp34_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp34_MuchoActionPerformed

    private void btn_DAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desarrolloView_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desarrolloView_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desarrolloView_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desarrolloView_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desarrolloView_0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Dp11;
    private javax.swing.JLabel L_Dp12;
    private javax.swing.JLabel L_Dp2;
    private javax.swing.JLabel L_Dp33;
    private javax.swing.JLabel L_Dp34;
    private javax.swing.JLabel L_p21;
    private javax.swing.JLabel L_p22;
    private javax.swing.JLabel L_p23;
    private javax.swing.JLabel L_p25;
    private javax.swing.JLabel L_p33_2;
    private javax.swing.JLabel L_p35;
    private javax.swing.JLabel L_p36;
    private javax.swing.JLabel L_p37;
    private javax.swing.JLabel L_p38;
    private javax.swing.JLabel L_p39;
    private javax.swing.JButton btn_DAtras;
    private javax.swing.JButton btn_DSiguiente;
    private javax.swing.JCheckBox checkB_Inv_Dp1;
    private javax.swing.JCheckBox checkB_Inv_Dp21;
    private javax.swing.JCheckBox checkB_Inv_Dp22;
    private javax.swing.JCheckBox checkB_Inv_Dp23;
    private javax.swing.JCheckBox checkB_Inv_Dp34;
    private javax.swing.JCheckBox checkB_Inv_Dp35;
    private javax.swing.JCheckBox checkB_Inv_Dp36;
    private javax.swing.JCheckBox checkB_Inv_Dp37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_Dp1;
    private javax.swing.JPanel pnl_Dp2;
    private javax.swing.JPanel pnl_Dp21;
    private javax.swing.JPanel pnl_Dp22;
    private javax.swing.JPanel pnl_Dp23;
    private javax.swing.JPanel pnl_Dp34;
    private javax.swing.JPanel pnl_Dp35;
    private javax.swing.JPanel pnl_Dp36;
    private javax.swing.JPanel pnl_Dp4;
    private javax.swing.JPanel pnl_Dr2;
    private javax.swing.JPanel pnl_Dr21;
    private javax.swing.JPanel pnl_Dr22;
    private javax.swing.JPanel pnl_Dr23;
    private javax.swing.JPanel pnl_Dr3;
    private javax.swing.JPanel pnl_Dr31;
    private javax.swing.JPanel pnl_Dr33;
    private javax.swing.JPanel pnl_Dr38;
    private javax.swing.JPanel pnl_Dr4;
    private javax.swing.JPanel pnl_r1D;
    private javax.swing.JRadioButton rbn_2017_2018;
    private javax.swing.JRadioButton rbn_2018_2019;
    private javax.swing.JRadioButton rbn_descono;
    private javax.swing.ButtonGroup rbtnG_Dp1;
    private javax.swing.ButtonGroup rbtnG_Dp21;
    private javax.swing.ButtonGroup rbtnG_Dp22;
    private javax.swing.ButtonGroup rbtnG_Dp23;
    private javax.swing.ButtonGroup rbtnG_Dp31;
    private javax.swing.ButtonGroup rbtnG_Dp32;
    private javax.swing.ButtonGroup rbtnG_Dp33;
    private javax.swing.ButtonGroup rbtnG_Dp34;
    private javax.swing.JRadioButton rbtn_2016_2017;
    private javax.swing.JRadioButton rbtn_Dp21_Mucho;
    private javax.swing.JRadioButton rbtn_Dp21_Nada;
    private javax.swing.JRadioButton rbtn_Dp21_Poco;
    private javax.swing.JRadioButton rbtn_Dp21_Regular;
    private javax.swing.JRadioButton rbtn_Dp22_Mucho;
    private javax.swing.JRadioButton rbtn_Dp22_Nada;
    private javax.swing.JRadioButton rbtn_Dp22_Poco;
    private javax.swing.JRadioButton rbtn_Dp22_Regular;
    private javax.swing.JRadioButton rbtn_Dp23_Mucho;
    private javax.swing.JRadioButton rbtn_Dp23_Nada;
    private javax.swing.JRadioButton rbtn_Dp23_Poco;
    private javax.swing.JRadioButton rbtn_Dp23_Regular;
    private javax.swing.JRadioButton rbtn_Dp31_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp31_Nada1;
    private javax.swing.JRadioButton rbtn_Dp31_Poco1;
    private javax.swing.JRadioButton rbtn_Dp31_Regular1;
    private javax.swing.JRadioButton rbtn_Dp32_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp32_Nada1;
    private javax.swing.JRadioButton rbtn_Dp32_Poco1;
    private javax.swing.JRadioButton rbtn_Dp32_Regular1;
    private javax.swing.JRadioButton rbtn_Dp33_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp33_Nada1;
    private javax.swing.JRadioButton rbtn_Dp33_Poco1;
    private javax.swing.JRadioButton rbtn_Dp33_Regular1;
    private javax.swing.JRadioButton rbtn_Dp34_Mucho;
    private javax.swing.JRadioButton rbtn_Dp34_Nada;
    private javax.swing.JRadioButton rbtn_Dp34_Poco;
    private javax.swing.JRadioButton rbtn_Dp34_Regular;
    // End of variables declaration//GEN-END:variables
}
