/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author astri
 */
public class desarrolloView extends javax.swing.JFrame {

    /**
     * Creates new form desarrolloView
     */
    public desarrolloView() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        rbtnG_Dp1.add(rbtn_2016_2017);
        rbtnG_Dp1.add(rbn_2017_2018);
        rbtnG_Dp1.add(rbn_2018_2019);
        rbtnG_Dp1.add(rbn_descono);
        
        rbtnG_Dp21.add(rbtn_Dp21_Mucho);
        rbtnG_Dp21.add(rbtn_Dp21_Regular);
        rbtnG_Dp21.add(rbtn_Dp21_Poco);
        rbtnG_Dp21.add(rbtn_Dp21_Nada);
        
        
        rbtnG_Dp22.add(rbtn_Dp22_Mucho);
        rbtnG_Dp22.add(rbtn_Dp22_Regular);
        rbtnG_Dp22.add(rbtn_Dp22_Poco);
        rbtnG_Dp22.add(rbtn_Dp22_Nada);
        
        rbtnG_Dp23.add(rbtn_Dp23_Mucho);
        rbtnG_Dp23.add(rbtn_Dp23_Regular);
        rbtnG_Dp23.add(rbtn_Dp23_Poco);
        rbtnG_Dp23.add(rbtn_Dp23_Nada);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnG_Dp1 = new javax.swing.ButtonGroup();
        rbtnG_Dp21 = new javax.swing.ButtonGroup();
        rbtnG_Dp22 = new javax.swing.ButtonGroup();
        rbtnG_Dp23 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnl_Dp1 = new javax.swing.JPanel();
        L_Dp11 = new javax.swing.JLabel();
        pnl_r1D = new javax.swing.JPanel();
        rbtn_2016_2017 = new javax.swing.JRadioButton();
        rbn_2017_2018 = new javax.swing.JRadioButton();
        rbn_2018_2019 = new javax.swing.JRadioButton();
        rbn_descono = new javax.swing.JRadioButton();
        checkB_Inv_Dp1 = new javax.swing.JCheckBox();
        L_Dp12 = new javax.swing.JLabel();
        pnl_Dp2 = new javax.swing.JPanel();
        L_Dp2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnl_Dp21 = new javax.swing.JPanel();
        pnl_r1D1 = new javax.swing.JPanel();
        rbtn_Dp21_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp21_Regular = new javax.swing.JRadioButton();
        rbtn_Dp21_Poco = new javax.swing.JRadioButton();
        rbtn_Dp21_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp21 = new javax.swing.JCheckBox();
        L_p21 = new javax.swing.JLabel();
        pnl_Dp22 = new javax.swing.JPanel();
        pnl_r1D2 = new javax.swing.JPanel();
        rbtn_Dp22_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp22_Regular = new javax.swing.JRadioButton();
        rbtn_Dp22_Poco = new javax.swing.JRadioButton();
        rbtn_Dp22_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp22 = new javax.swing.JCheckBox();
        L_p22 = new javax.swing.JLabel();
        pnl_Dp23 = new javax.swing.JPanel();
        pnl_r1D3 = new javax.swing.JPanel();
        rbtn_Dp23_Mucho = new javax.swing.JRadioButton();
        rbtn_Dp23_Regular = new javax.swing.JRadioButton();
        rbtn_Dp23_Poco = new javax.swing.JRadioButton();
        rbtn_Dp23_Nada = new javax.swing.JRadioButton();
        checkB_Inv_Dp23 = new javax.swing.JCheckBox();
        L_p23 = new javax.swing.JLabel();
        pnl_Dp3 = new javax.swing.JPanel();
        L_Dp31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnl_Dp27 = new javax.swing.JPanel();
        pnl_r1D7 = new javax.swing.JPanel();
        rbtn_Dp21_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp21_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp21_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp21_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp24 = new javax.swing.JCheckBox();
        L_p27 = new javax.swing.JLabel();
        pnl_Dp28 = new javax.swing.JPanel();
        pnl_r1D8 = new javax.swing.JPanel();
        rbtn_Dp22_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp22_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp22_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp22_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp25 = new javax.swing.JCheckBox();
        L_p28 = new javax.swing.JLabel();
        pnl_Dp29 = new javax.swing.JPanel();
        pnl_r1D9 = new javax.swing.JPanel();
        rbtn_Dp23_Mucho1 = new javax.swing.JRadioButton();
        rbtn_Dp23_Regular1 = new javax.swing.JRadioButton();
        rbtn_Dp23_Poco1 = new javax.swing.JRadioButton();
        rbtn_Dp23_Nada1 = new javax.swing.JRadioButton();
        checkB_Inv_Dp26 = new javax.swing.JCheckBox();
        L_p29 = new javax.swing.JLabel();
        L_Dp32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 750));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        L_Dp11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp11.setText("1. Señale el ciclo escolar en que su escuela ha estado adscrita al Programa Nacional de Convivencia Escolar (puede");

        rbtn_2016_2017.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_2016_2017.setText("2016 - 2017");
        rbtn_2016_2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_2016_2017ActionPerformed(evt);
            }
        });

        rbn_2017_2018.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2017_2018.setText("2017 - 2018");
        rbn_2017_2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_2017_2018ActionPerformed(evt);
            }
        });

        rbn_2018_2019.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_2018_2019.setText("2018-2019");

        rbn_descono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_descono.setText("Lo desconozco");

        checkB_Inv_Dp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp1.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp1.setText("Invalidar pregunta");
        checkB_Inv_Dp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1DLayout = new javax.swing.GroupLayout(pnl_r1D);
        pnl_r1D.setLayout(pnl_r1DLayout);
        pnl_r1DLayout.setHorizontalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_2016_2017)
                .addGap(60, 60, 60)
                .addComponent(rbn_2017_2018)
                .addGap(90, 90, 90)
                .addComponent(rbn_2018_2019)
                .addGap(90, 90, 90)
                .addComponent(rbn_descono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp1)
                .addGap(58, 58, 58))
        );
        pnl_r1DLayout.setVerticalGroup(
            pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1DLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_2016_2017)
                    .addComponent(rbn_2017_2018)
                    .addComponent(rbn_2018_2019)
                    .addComponent(rbn_descono)
                    .addComponent(checkB_Inv_Dp1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        L_Dp12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp12.setText("mencionar más de uno):");

        javax.swing.GroupLayout pnl_Dp1Layout = new javax.swing.GroupLayout(pnl_Dp1);
        pnl_Dp1.setLayout(pnl_Dp1Layout);
        pnl_Dp1Layout.setHorizontalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Dp12)
                    .addComponent(L_Dp11, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp1Layout.setVerticalGroup(
            pnl_Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Dp11)
                .addGap(10, 10, 10)
                .addComponent(L_Dp12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_r1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Dp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp2.setText("2. Del Programa Nacional de Convivencia Escolar, en qué medida conoce:");

        rbtn_Dp21_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Mucho.setText("Mucho");
        rbtn_Dp21_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp21_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Regular.setText("Regular");
        rbtn_Dp21_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp21_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Poco.setText("Poco");

        rbtn_Dp21_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Nada.setText("Nada");

        checkB_Inv_Dp21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp21.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp21.setText("Invalidar pregunta");
        checkB_Inv_Dp21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D1Layout = new javax.swing.GroupLayout(pnl_r1D1);
        pnl_r1D1.setLayout(pnl_r1D1Layout);
        pnl_r1D1Layout.setHorizontalGroup(
            pnl_r1D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp21_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp21)
                .addContainerGap())
        );
        pnl_r1D1Layout.setVerticalGroup(
            pnl_r1D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp21_Mucho)
                    .addComponent(rbtn_Dp21_Regular)
                    .addComponent(rbtn_Dp21_Poco)
                    .addComponent(rbtn_Dp21_Nada)
                    .addComponent(checkB_Inv_Dp21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p21.setText("El objetivo que persigue.");

        javax.swing.GroupLayout pnl_Dp21Layout = new javax.swing.GroupLayout(pnl_Dp21);
        pnl_Dp21.setLayout(pnl_Dp21Layout);
        pnl_Dp21Layout.setHorizontalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_r1D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp21Layout.setVerticalGroup(
            pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp21Layout.createSequentialGroup()
                        .addComponent(pnl_r1D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(L_p21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        rbtn_Dp22_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Mucho.setText("Mucho");
        rbtn_Dp22_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp22_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Regular.setText("Regular");
        rbtn_Dp22_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp22_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Poco.setText("Poco");

        rbtn_Dp22_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Nada.setText("Nada");

        checkB_Inv_Dp22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp22.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp22.setText("Invalidar pregunta");
        checkB_Inv_Dp22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D2Layout = new javax.swing.GroupLayout(pnl_r1D2);
        pnl_r1D2.setLayout(pnl_r1D2Layout);
        pnl_r1D2Layout.setHorizontalGroup(
            pnl_r1D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp22_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp22)
                .addContainerGap())
        );
        pnl_r1D2Layout.setVerticalGroup(
            pnl_r1D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp22_Mucho)
                    .addComponent(rbtn_Dp22_Regular)
                    .addComponent(rbtn_Dp22_Poco)
                    .addComponent(rbtn_Dp22_Nada)
                    .addComponent(checkB_Inv_Dp22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p22.setText("Las personas a quienes va dirigido");

        javax.swing.GroupLayout pnl_Dp22Layout = new javax.swing.GroupLayout(pnl_Dp22);
        pnl_Dp22.setLayout(pnl_Dp22Layout);
        pnl_Dp22Layout.setHorizontalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p22, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(pnl_r1D2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_Dp22Layout.setVerticalGroup(
            pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp22Layout.createSequentialGroup()
                .addGroup(pnl_Dp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(L_p22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_r1D2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rbtn_Dp23_Mucho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Mucho.setText("Mucho");
        rbtn_Dp23_Mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_MuchoActionPerformed(evt);
            }
        });

        rbtn_Dp23_Regular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Regular.setText("Regular");
        rbtn_Dp23_Regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_RegularActionPerformed(evt);
            }
        });

        rbtn_Dp23_Poco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Poco.setText("Poco");

        rbtn_Dp23_Nada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Nada.setText("Nada");

        checkB_Inv_Dp23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp23.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp23.setText("Invalidar pregunta");
        checkB_Inv_Dp23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D3Layout = new javax.swing.GroupLayout(pnl_r1D3);
        pnl_r1D3.setLayout(pnl_r1D3Layout);
        pnl_r1D3Layout.setHorizontalGroup(
            pnl_r1D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp23_Mucho)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Regular)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Poco)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp23)
                .addGap(14, 14, 14))
        );
        pnl_r1D3Layout.setVerticalGroup(
            pnl_r1D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp23_Mucho)
                    .addComponent(rbtn_Dp23_Regular)
                    .addComponent(rbtn_Dp23_Poco)
                    .addComponent(rbtn_Dp23_Nada)
                    .addComponent(checkB_Inv_Dp23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p23.setText("Los materiales diseñados (guías, manuales y cuadernos)");

        javax.swing.GroupLayout pnl_Dp23Layout = new javax.swing.GroupLayout(pnl_Dp23);
        pnl_Dp23.setLayout(pnl_Dp23Layout);
        pnl_Dp23Layout.setHorizontalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p23, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(pnl_r1D3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp23Layout.setVerticalGroup(
            pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp23Layout.createSequentialGroup()
                .addGroup(pnl_Dp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_r1D3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_p23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_Dp23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Dp2Layout = new javax.swing.GroupLayout(pnl_Dp2);
        pnl_Dp2.setLayout(pnl_Dp2Layout);
        pnl_Dp2Layout.setHorizontalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp2Layout.createSequentialGroup()
                        .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_Dp2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_Dp2Layout.setVerticalGroup(
            pnl_Dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(L_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        L_Dp31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp31.setText("3. En qué medida considera que se han cumplido los alcances del Programa Nacional de Convivencia Escolar en su");

        rbtn_Dp21_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Mucho1.setText("Mucho");
        rbtn_Dp21_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp21_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Regular1.setText("Regular");
        rbtn_Dp21_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp21_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp21_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Poco1.setText("Poco");

        rbtn_Dp21_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp21_Nada1.setText("Nada");

        checkB_Inv_Dp24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp24.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp24.setText("Invalidar pregunta");
        checkB_Inv_Dp24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D7Layout = new javax.swing.GroupLayout(pnl_r1D7);
        pnl_r1D7.setLayout(pnl_r1D7Layout);
        pnl_r1D7Layout.setHorizontalGroup(
            pnl_r1D7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp21_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp21_Nada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp24)
                .addContainerGap())
        );
        pnl_r1D7Layout.setVerticalGroup(
            pnl_r1D7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp21_Mucho1)
                    .addComponent(rbtn_Dp21_Regular1)
                    .addComponent(rbtn_Dp21_Poco1)
                    .addComponent(rbtn_Dp21_Nada1)
                    .addComponent(checkB_Inv_Dp24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p27.setText("El objetivo que persigue.");

        javax.swing.GroupLayout pnl_Dp27Layout = new javax.swing.GroupLayout(pnl_Dp27);
        pnl_Dp27.setLayout(pnl_Dp27Layout);
        pnl_Dp27Layout.setHorizontalGroup(
            pnl_Dp27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_r1D7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_Dp27Layout.setVerticalGroup(
            pnl_Dp27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Dp27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp27Layout.createSequentialGroup()
                        .addComponent(pnl_r1D7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(L_p27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        rbtn_Dp22_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Mucho1.setText("Mucho");
        rbtn_Dp22_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp22_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Regular1.setText("Regular");
        rbtn_Dp22_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp22_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp22_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Poco1.setText("Poco");

        rbtn_Dp22_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp22_Nada1.setText("Nada");

        checkB_Inv_Dp25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp25.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp25.setText("Invalidar pregunta");
        checkB_Inv_Dp25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D8Layout = new javax.swing.GroupLayout(pnl_r1D8);
        pnl_r1D8.setLayout(pnl_r1D8Layout);
        pnl_r1D8Layout.setHorizontalGroup(
            pnl_r1D8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp22_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp22_Nada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp25)
                .addContainerGap())
        );
        pnl_r1D8Layout.setVerticalGroup(
            pnl_r1D8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp22_Mucho1)
                    .addComponent(rbtn_Dp22_Regular1)
                    .addComponent(rbtn_Dp22_Poco1)
                    .addComponent(rbtn_Dp22_Nada1)
                    .addComponent(checkB_Inv_Dp25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p28.setText("Las personas a quienes va dirigido");

        javax.swing.GroupLayout pnl_Dp28Layout = new javax.swing.GroupLayout(pnl_Dp28);
        pnl_Dp28.setLayout(pnl_Dp28Layout);
        pnl_Dp28Layout.setHorizontalGroup(
            pnl_Dp28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p28, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(pnl_r1D8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_Dp28Layout.setVerticalGroup(
            pnl_Dp28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp28Layout.createSequentialGroup()
                .addGroup(pnl_Dp28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(L_p28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_r1D8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rbtn_Dp23_Mucho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Mucho1.setText("Mucho");
        rbtn_Dp23_Mucho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_Mucho1ActionPerformed(evt);
            }
        });

        rbtn_Dp23_Regular1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Regular1.setText("Regular");
        rbtn_Dp23_Regular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Dp23_Regular1ActionPerformed(evt);
            }
        });

        rbtn_Dp23_Poco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Poco1.setText("Poco");

        rbtn_Dp23_Nada1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_Dp23_Nada1.setText("Nada");

        checkB_Inv_Dp26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkB_Inv_Dp26.setForeground(new java.awt.Color(255, 0, 0));
        checkB_Inv_Dp26.setText("Invalidar pregunta");
        checkB_Inv_Dp26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_Inv_Dp26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_r1D9Layout = new javax.swing.GroupLayout(pnl_r1D9);
        pnl_r1D9.setLayout(pnl_r1D9Layout);
        pnl_r1D9Layout.setHorizontalGroup(
            pnl_r1D9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Dp23_Mucho1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Regular1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Poco1)
                .addGap(30, 30, 30)
                .addComponent(rbtn_Dp23_Nada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkB_Inv_Dp26)
                .addGap(14, 14, 14))
        );
        pnl_r1D9Layout.setVerticalGroup(
            pnl_r1D9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_r1D9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_r1D9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Dp23_Mucho1)
                    .addComponent(rbtn_Dp23_Regular1)
                    .addComponent(rbtn_Dp23_Poco1)
                    .addComponent(rbtn_Dp23_Nada1)
                    .addComponent(checkB_Inv_Dp26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_p29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_p29.setText("Los materiales diseñados (guías, manuales y cuadernos)");

        javax.swing.GroupLayout pnl_Dp29Layout = new javax.swing.GroupLayout(pnl_Dp29);
        pnl_Dp29.setLayout(pnl_Dp29Layout);
        pnl_Dp29Layout.setHorizontalGroup(
            pnl_Dp29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Dp29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_p29, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(pnl_r1D9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Dp29Layout.setVerticalGroup(
            pnl_Dp29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp29Layout.createSequentialGroup()
                .addGroup(pnl_Dp29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_r1D9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_p29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_Dp29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Dp32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Dp32.setText("escuela, en relación con:");

        javax.swing.GroupLayout pnl_Dp3Layout = new javax.swing.GroupLayout(pnl_Dp3);
        pnl_Dp3.setLayout(pnl_Dp3Layout);
        pnl_Dp3Layout.setHorizontalGroup(
            pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp3Layout.createSequentialGroup()
                .addGroup(pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Dp3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(L_Dp32, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Dp3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Dp31, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnl_Dp3Layout.setVerticalGroup(
            pnl_Dp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Dp3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(L_Dp31, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Dp32, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Dp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Dp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Dp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Dp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_2016_2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_2016_2017ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_2016_2017ActionPerformed

    private void rbn_2017_2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_2017_2018ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_2017_2018ActionPerformed

    private void rbtn_Dp21_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_MuchoActionPerformed

    private void rbtn_Dp21_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_RegularActionPerformed

    private void rbtn_Dp22_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_MuchoActionPerformed

    private void rbtn_Dp22_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_RegularActionPerformed

    private void rbtn_Dp23_MuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_MuchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_MuchoActionPerformed

    private void rbtn_Dp23_RegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_RegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_RegularActionPerformed

    private void checkB_Inv_Dp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp1ActionPerformed

    private void checkB_Inv_Dp21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp21ActionPerformed

    private void checkB_Inv_Dp22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp22ActionPerformed

    private void checkB_Inv_Dp23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp23ActionPerformed

    private void rbtn_Dp21_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_Mucho1ActionPerformed

    private void rbtn_Dp21_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp21_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp21_Regular1ActionPerformed

    private void checkB_Inv_Dp24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp24ActionPerformed

    private void rbtn_Dp22_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_Mucho1ActionPerformed

    private void rbtn_Dp22_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp22_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp22_Regular1ActionPerformed

    private void checkB_Inv_Dp25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp25ActionPerformed

    private void rbtn_Dp23_Mucho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_Mucho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_Mucho1ActionPerformed

    private void rbtn_Dp23_Regular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Dp23_Regular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Dp23_Regular1ActionPerformed

    private void checkB_Inv_Dp26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_Inv_Dp26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_Inv_Dp26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desarrolloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desarrolloView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Dp11;
    private javax.swing.JLabel L_Dp12;
    private javax.swing.JLabel L_Dp2;
    private javax.swing.JLabel L_Dp31;
    private javax.swing.JLabel L_Dp32;
    private javax.swing.JLabel L_p21;
    private javax.swing.JLabel L_p22;
    private javax.swing.JLabel L_p23;
    private javax.swing.JLabel L_p27;
    private javax.swing.JLabel L_p28;
    private javax.swing.JLabel L_p29;
    private javax.swing.JCheckBox checkB_Inv_Dp1;
    private javax.swing.JCheckBox checkB_Inv_Dp21;
    private javax.swing.JCheckBox checkB_Inv_Dp22;
    private javax.swing.JCheckBox checkB_Inv_Dp23;
    private javax.swing.JCheckBox checkB_Inv_Dp24;
    private javax.swing.JCheckBox checkB_Inv_Dp25;
    private javax.swing.JCheckBox checkB_Inv_Dp26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_Dp1;
    private javax.swing.JPanel pnl_Dp2;
    private javax.swing.JPanel pnl_Dp21;
    private javax.swing.JPanel pnl_Dp22;
    private javax.swing.JPanel pnl_Dp23;
    private javax.swing.JPanel pnl_Dp27;
    private javax.swing.JPanel pnl_Dp28;
    private javax.swing.JPanel pnl_Dp29;
    private javax.swing.JPanel pnl_Dp3;
    private javax.swing.JPanel pnl_r1D;
    private javax.swing.JPanel pnl_r1D1;
    private javax.swing.JPanel pnl_r1D2;
    private javax.swing.JPanel pnl_r1D3;
    private javax.swing.JPanel pnl_r1D7;
    private javax.swing.JPanel pnl_r1D8;
    private javax.swing.JPanel pnl_r1D9;
    private javax.swing.JRadioButton rbn_2017_2018;
    private javax.swing.JRadioButton rbn_2018_2019;
    private javax.swing.JRadioButton rbn_descono;
    private javax.swing.ButtonGroup rbtnG_Dp1;
    private javax.swing.ButtonGroup rbtnG_Dp21;
    private javax.swing.ButtonGroup rbtnG_Dp22;
    private javax.swing.ButtonGroup rbtnG_Dp23;
    private javax.swing.JRadioButton rbtn_2016_2017;
    private javax.swing.JRadioButton rbtn_Dp21_Mucho;
    private javax.swing.JRadioButton rbtn_Dp21_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp21_Nada;
    private javax.swing.JRadioButton rbtn_Dp21_Nada1;
    private javax.swing.JRadioButton rbtn_Dp21_Poco;
    private javax.swing.JRadioButton rbtn_Dp21_Poco1;
    private javax.swing.JRadioButton rbtn_Dp21_Regular;
    private javax.swing.JRadioButton rbtn_Dp21_Regular1;
    private javax.swing.JRadioButton rbtn_Dp22_Mucho;
    private javax.swing.JRadioButton rbtn_Dp22_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp22_Nada;
    private javax.swing.JRadioButton rbtn_Dp22_Nada1;
    private javax.swing.JRadioButton rbtn_Dp22_Poco;
    private javax.swing.JRadioButton rbtn_Dp22_Poco1;
    private javax.swing.JRadioButton rbtn_Dp22_Regular;
    private javax.swing.JRadioButton rbtn_Dp22_Regular1;
    private javax.swing.JRadioButton rbtn_Dp23_Mucho;
    private javax.swing.JRadioButton rbtn_Dp23_Mucho1;
    private javax.swing.JRadioButton rbtn_Dp23_Nada;
    private javax.swing.JRadioButton rbtn_Dp23_Nada1;
    private javax.swing.JRadioButton rbtn_Dp23_Poco;
    private javax.swing.JRadioButton rbtn_Dp23_Poco1;
    private javax.swing.JRadioButton rbtn_Dp23_Regular;
    private javax.swing.JRadioButton rbtn_Dp23_Regular1;
    // End of variables declaration//GEN-END:variables
}
