/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app;

import surveyClasses.dataSurvey;

/**
 *
 * @author astri
 */
public class surveyTypes extends javax.swing.JFrame {
    public dataSurvey sv = new dataSurvey(); //This object is for setting the survey type when clicking the buttons.

    /** Creates new form tiposCuestionarios */
    public surveyTypes() {
        initComponents();
        this.setLocationRelativeTo(null);
        //btn_ViolenciaSurv.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_DesarrolloSurv = new java.awt.Button();
        btn_ViolenciaSurv = new java.awt.Button();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Encuestas");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        btn_DesarrolloSurv.setBackground(new java.awt.Color(51, 255, 0));
        btn_DesarrolloSurv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_DesarrolloSurv.setLabel("Encuesta Desarrollo del PNCE");
        btn_DesarrolloSurv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DesarrolloSurvActionPerformed(evt);
            }
        });

        btn_ViolenciaSurv.setBackground(new java.awt.Color(204, 153, 0));
        btn_ViolenciaSurv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_ViolenciaSurv.setLabel("Encuesta Violencia Escolar");
        btn_ViolenciaSurv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViolenciaSurvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_DesarrolloSurv, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(btn_ViolenciaSurv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btn_DesarrolloSurv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_ViolenciaSurv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btn_ViolenciaSurv.getAccessibleContext().setAccessibleName("btn_Desarrollo");

        btn_regresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_regresar.setText("Regresar al menú principal");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(btn_regresar)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btn_regresar)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DesarrolloSurvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DesarrolloSurvActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        this.sv.setEncuesta("DESARROLLO");
        System.out.println("survey type: " +this.sv.getEncuesta());
        this.sv.setFolio("D_");
        
        dataView datav = new dataView();
        datav.sv = this.sv;
        datav.encuesta_label.setText(datav.sv.getEncuesta());
        datav.btn_next.setEnabled(false);
        datav.setVisible(true);
       
        /*
        this.setVisible(false);
        dataSurvey svD  = new dataSurvey();
        //Creating a new dataSurvey for Desarrollo Survey
        svD.setEncuesta("DESARROLLO");
        svD.setFolio("D_");
        
        dataView dataViewD = new dataView();
        dataViewD.sv = svD;
        dataViewD.encuesta_label.setText(dataViewD.sv.getEncuesta());
        dataViewD.setVisible(true);
        */
        
    }//GEN-LAST:event_btn_DesarrolloSurvActionPerformed

    private void btn_ViolenciaSurvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViolenciaSurvActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.sv.setEncuesta("VIOLENCIA");
        System.out.println("survey type: " +this.sv.getEncuesta());
        this.sv.setFolio("V_");
        
        dataView datav = new dataView();
        datav.sv = this.sv;
        datav.encuesta_label.setText(datav.sv.getEncuesta());
        datav.btn_next.setEnabled(false);
        datav.setVisible(true);
        
        /*this.setVisible(false);
        dataSurvey svD  = new dataSurvey();
        //Creating a new dataSurvey for Desarrollo Survey
        svD.setEncuesta("VIOLENCIA");
        svD.setFolio("V_");
        
        dataView dataViewD = new dataView();
        dataViewD.sv = svD;
        dataViewD.encuesta_label.setText(dataViewD.sv.getEncuesta());
        dataViewD.setVisible(true);*/
    }//GEN-LAST:event_btn_ViolenciaSurvActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        mainMenu main = new mainMenu();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surveyTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surveyTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surveyTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surveyTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new surveyTypes().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_DesarrolloSurv;
    private java.awt.Button btn_ViolenciaSurv;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
